### PR TITLE
Ops cleanup

### PR DESCRIPTION
**Pull request by raorao**
a few minor back-end improvements

* we have a root route!
* use content-type declarations to clean some of the parsing stuff up. 
* switch update route to PATCH instead of POST
* cleans up back-end file structure
* cleans up README
* removes unused files
* also moves us to postgres you're welcome

### CODE REVIEW

**Comment by mknudsen01** [comment]
All looks lovely, @raorao. Thanks for the cleanup

**Comment by mknudsen01** [comment]
I'm getting some weird errors involving postgres when I try to run your branch. Will check out more tomorrow

**Comment by raorao** [comment]
yeah for sure

**Comment by raorao** [comment]
sorry I keep on accidentally pushing to master when i mean to push to heroku

**Pull request merged**
